#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/3bedda52fae42a9f58e88ab741db14d8f792592825b421df63901d0e1300b14b/contract';
import endContract from '../../snapshots/3bedda52fae42a9f58e88ab741db14d8f792592825b421df63901d0e1300b14b/contract.json' with { type: 'json' };
import { Migration, MigrationCLI, col, fn, lit, primaryKey } from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'AllergySeverity',
        members: ['MILD', 'MODERATE', 'SEVERE'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'AppointmentStatus',
        members: ['PENDING', 'CONFIRMED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', 'NO_SHOW'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'AppointmentType',
        members: ['IN_PERSON', 'TELECONSULTATION', 'HOME_VISIT'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'BloodType',
        members: [
          'A_POS',
          'A_NEG',
          'B_POS',
          'B_NEG',
          'AB_POS',
          'AB_NEG',
          'O_POS',
          'O_NEG',
          'UNKNOWN',
        ],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'BookingSource',
        members: ['STAFF', 'WALK_IN', 'PHONE', 'PATIENT_PORTAL'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'ClinicalListStatus',
        members: ['RECORDED', 'NONE_KNOWN', 'UNKNOWN'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'Relationship',
        members: ['HEAD', 'SPOUSE', 'CHILD', 'PARENT', 'SIBLING', 'GRANDPARENT', 'OTHER'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'ReminderPreference',
        members: ['NONE', 'SMS', 'EMAIL', 'APP'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'ServiceType',
        members: [
          'GENERAL_CONSULTATION',
          'FAMILY_CHECKUP',
          'FOLLOW_UP_CHECKUP',
          'ROUTINE_PHYSICAL_EXAM',
          'PEDIATRIC_CONSULTATION',
          'SENIOR_CITIZEN_CONSULTATION',
          'PRENATAL_POSTNATAL_CONSULTATION',
          'CHRONIC_DISEASE_MANAGEMENT',
          'PRESCRIPTION_RENEWAL',
          'LABORATORY_RESULT_REVIEW',
          'MEDICAL_CERTIFICATE_REQUEST',
          'VACCINATION_CONSULTATION',
          'MINOR_INJURY_WOUND_CARE',
          'TELECONSULTATION',
          'REFERRAL_CONSULTATION',
        ],
      }),
      this.createNativeEnumType({ schema: 'public', typeName: 'Sex', members: ['MALE', 'FEMALE'] }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'VisitPriority',
        members: ['ROUTINE', 'URGENT', 'FOLLOW_UP'],
      }),
      this.createTable({
        schema: 'public',
        table: 'Appointment',
        columns: [
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('doctorId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('durationMinutes', 'int4', {
            notNull: true,
            default: lit(30),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('internalNotes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('patientId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('previousAppointmentId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('priority', '"VisitPriority"', {
            notNull: true,
            default: lit('ROUTINE'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'VisitPriority' } },
          }),
          col('reason', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('reminderPreference', '"ReminderPreference"', {
            notNull: true,
            default: lit('NONE'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'ReminderPreference' } },
          }),
          col('room', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('scheduledAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('service', '"ServiceType"', {
            notNull: true,
            default: lit('GENERAL_CONSULTATION'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'ServiceType' } },
          }),
          col('source', '"BookingSource"', {
            notNull: true,
            default: lit('STAFF'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'BookingSource' } },
          }),
          col('status', '"AppointmentStatus"', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'AppointmentStatus' } },
          }),
          col('type', '"AppointmentType"', {
            notNull: true,
            default: lit('IN_PERSON'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'AppointmentType' } },
          }),
          col('updatedAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'Appointment_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Doctor',
        columns: [
          col('clinicName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('fullName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('licenseNumber', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('passwordHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('specialty', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'Doctor_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Household',
        columns: [
          col('address', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('contactNumber', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('doctorId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'Household_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'MedicalRecord',
        columns: [
          col('appointmentId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('assessment', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('chiefComplaint', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('diastolic', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('doctorId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('followUpAppointmentId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('followUpDate', 'date', { codecRef: { codecId: 'pg/date-string@1' } }),
          col('heartRate', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('heightCm', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('historyOfPresentIllness', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('oxygenSaturation', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('patientId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('physicalExamination', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('respiratoryRate', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('systolic', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('temperatureC', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('treatmentPlan', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('visitDate', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('weightKg', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'MedicalRecord_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Patient',
        columns: [
          col('allergyStatus', '"ClinicalListStatus"', {
            notNull: true,
            default: lit('UNKNOWN'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'ClinicalListStatus' } },
          }),
          col('bloodType', '"BloodType"', {
            notNull: true,
            default: lit('UNKNOWN'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'BloodType' } },
          }),
          col('conditionStatus', '"ClinicalListStatus"', {
            notNull: true,
            default: lit('UNKNOWN'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'ClinicalListStatus' } },
          }),
          col('contactNumber', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('dateOfBirth', 'date', { notNull: true, codecRef: { codecId: 'pg/date-string@1' } }),
          col('email', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('firstName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('householdId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('middleName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('relationship', '"Relationship"', {
            notNull: true,
            default: lit('OTHER'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'Relationship' } },
          }),
          col('sex', '"Sex"', {
            notNull: true,
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'Sex' } },
          }),
          col('updatedAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'Patient_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'PatientAllergy',
        columns: [
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('label', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('patientId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('reaction', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('severity', '"AllergySeverity"', {
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'AllergySeverity' } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'PatientAllergy_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'PatientCondition',
        columns: [
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('label', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('patientId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'PatientCondition_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Prescription',
        columns: [
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('dosage', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('drugName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('duration', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('frequency', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('instructions', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('medicalRecordId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'Prescription_pkey' })],
      }),
      this.addUnique({
        schema: 'public',
        table: 'MedicalRecord',
        constraint: 'MedicalRecord_appointmentId_key',
        columns: ['appointmentId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'MedicalRecord',
        constraint: 'MedicalRecord_followUpAppointmentId_key',
        columns: ['followUpAppointmentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Appointment',
        index: 'Appointment_doctorId_scheduledAt_idx',
        columns: ['doctorId', 'scheduledAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Appointment',
        index: 'Appointment_patientId_idx',
        columns: ['patientId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Appointment',
        index: 'Appointment_previousAppointmentId_idx',
        columns: ['previousAppointmentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Doctor',
        index: 'Doctor_email_key',
        columns: ['email'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'Household',
        index: 'Household_doctorId_idx',
        columns: ['doctorId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Household',
        index: 'Household_doctorId_name_key',
        columns: ['doctorId', 'name'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'MedicalRecord',
        index: 'MedicalRecord_doctorId_idx',
        columns: ['doctorId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'MedicalRecord',
        index: 'MedicalRecord_patientId_visitDate_idx',
        columns: ['patientId', 'visitDate'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Patient',
        index: 'Patient_householdId_idx',
        columns: ['householdId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Patient',
        index: 'Patient_lastName_firstName_idx',
        columns: ['lastName', 'firstName'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'PatientAllergy',
        index: 'PatientAllergy_patientId_idx',
        columns: ['patientId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'PatientAllergy',
        index: 'PatientAllergy_patientId_label_key',
        columns: ['patientId', 'label'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'PatientCondition',
        index: 'PatientCondition_patientId_idx',
        columns: ['patientId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'PatientCondition',
        index: 'PatientCondition_patientId_label_key',
        columns: ['patientId', 'label'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'Prescription',
        index: 'Prescription_medicalRecordId_idx',
        columns: ['medicalRecordId'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Appointment',
        foreignKey: {
          name: 'Appointment_doctorId_fkey',
          columns: ['doctorId'],
          references: { schema: 'public', table: 'Doctor', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Appointment',
        foreignKey: {
          name: 'Appointment_patientId_fkey',
          columns: ['patientId'],
          references: { schema: 'public', table: 'Patient', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Appointment',
        foreignKey: {
          name: 'Appointment_previousAppointmentId_fkey',
          columns: ['previousAppointmentId'],
          references: { schema: 'public', table: 'Appointment', columns: ['id'] },
          onDelete: 'setNull',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Household',
        foreignKey: {
          name: 'Household_doctorId_fkey',
          columns: ['doctorId'],
          references: { schema: 'public', table: 'Doctor', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MedicalRecord',
        foreignKey: {
          name: 'MedicalRecord_appointmentId_fkey',
          columns: ['appointmentId'],
          references: { schema: 'public', table: 'Appointment', columns: ['id'] },
          onDelete: 'setNull',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MedicalRecord',
        foreignKey: {
          name: 'MedicalRecord_doctorId_fkey',
          columns: ['doctorId'],
          references: { schema: 'public', table: 'Doctor', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MedicalRecord',
        foreignKey: {
          name: 'MedicalRecord_followUpAppointmentId_fkey',
          columns: ['followUpAppointmentId'],
          references: { schema: 'public', table: 'Appointment', columns: ['id'] },
          onDelete: 'setNull',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'MedicalRecord',
        foreignKey: {
          name: 'MedicalRecord_patientId_fkey',
          columns: ['patientId'],
          references: { schema: 'public', table: 'Patient', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Patient',
        foreignKey: {
          name: 'Patient_householdId_fkey',
          columns: ['householdId'],
          references: { schema: 'public', table: 'Household', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'PatientAllergy',
        foreignKey: {
          name: 'PatientAllergy_patientId_fkey',
          columns: ['patientId'],
          references: { schema: 'public', table: 'Patient', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'PatientCondition',
        foreignKey: {
          name: 'PatientCondition_patientId_fkey',
          columns: ['patientId'],
          references: { schema: 'public', table: 'Patient', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Prescription',
        foreignKey: {
          name: 'Prescription_medicalRecordId_fkey',
          columns: ['medicalRecordId'],
          references: { schema: 'public', table: 'MedicalRecord', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
