-- CreateEnum
CREATE TYPE "ServiceType" AS ENUM ('GENERAL_CONSULTATION', 'FAMILY_CHECKUP', 'FOLLOW_UP_CHECKUP', 'ROUTINE_PHYSICAL_EXAM', 'PEDIATRIC_CONSULTATION', 'SENIOR_CITIZEN_CONSULTATION', 'PRENATAL_POSTNATAL_CONSULTATION', 'CHRONIC_DISEASE_MANAGEMENT', 'PRESCRIPTION_RENEWAL', 'LABORATORY_RESULT_REVIEW', 'MEDICAL_CERTIFICATE_REQUEST', 'VACCINATION_CONSULTATION', 'MINOR_INJURY_WOUND_CARE', 'TELECONSULTATION', 'REFERRAL_CONSULTATION');

-- AlterTable
ALTER TABLE "Appointment" ADD COLUMN     "service" "ServiceType" NOT NULL DEFAULT 'GENERAL_CONSULTATION';
